### ISSUE TITLE
Editing categories in apps with multiple categories results in hard-to-read overlay

### ISSUE THREAD

**Issue by kindall** [spocky/miproja1#77] opened 2024-04-04 03:23 UTC
Settings > Edit channels > Pick an app that has multiple channels (e.g. YouTube)

Select a channel to edit it

The transparency of the menu allows you to see the list of channels underneath it, making it hard to read. Looks like the root cause could be the app list is sliding back out under it? Disabling "Allow window-level blurs" in developer settings is a workaround.

Projectivy 4.5.1, CCwGTV

**Comment by spocky** [comment] 2024-04-04 16:31
While I totally understand what you say (I've seen this behavior on the emulator, but I blamed it and my graphic drivers), I can't reproduce it on my CCwGTV or any onther physical device: here, when I'm entering a submenu, the previous menu fades out (and fades in when I click "back").
What's the OS version of your CCwGTV ? Did you change anything special in the settings (or in the developper settings) ?

<img width="617" alt="ss" src="https://github.com/spocky/miproja1/assets/809347/c065c7a7-c8e6-4cd1-abe9-8cbd331fcfda">

**Comment by pawel54321** [comment] 2024-04-04 17:55
I have this same problem. I see both menu in Chromecast when select "sub-category"

**Comment by spocky** [comment] 2024-04-04 21:51
> I have this same problem. I see both menu in Chromecast when select "sub-category"

What's the OS version of your CCwGTV ? Did you change anything special in the settings (or in the developper settings) ?
Whatever I try to change in the developer settings, I can't reproduce this : when entering submenus in the settings, the previous settings screen scrolls to the left while fading out (and when I click "back", it scrolls to the right while fadin in).

**Comment by pawel54321** [comment] 2024-04-05 15:07
> > I have this same problem. I see both menu in Chromecast when select "sub-category"
> 
> What's the OS version of your CCwGTV ? Did you change anything special in the settings (or in the developper settings) ? Whatever I try to change in the developer settings, I can't reproduce this : when entering submenus in the settings, the previous settings screen scrolls to the left while fading out (and when I click "back", it scrolls to the right while fadin in).



I have Chromecast 4.0 4k Projectivity Launcher 4.51. BUT option "Allow window-level blurs" don't fix this - nothing fix. I have only active (if good translate to english) "don't sleep display" and "descritpion wifi" - ssid. We need screenshot with my TV?

**Comment by spocky** [comment] 2024-04-05 18:50
I think I managed to reproduce it (it only happens when you first configure a channel after closing it from the list. Once activated, it works normally, that's why I couldn't reproduce it in the first place)

**Comment by pawel54321** [comment] 2024-04-05 19:07
> I think I managed to reproduce it (it only happens when you first configure a channel after closing it from the list. Once activated, it works normally, that's why I couldn't reproduce it in the first place)

I send photos. I have this problem always when I want show "sub-category" - Video Google Play example:

![IMG_20240405_205920754_HDR](https://github.com/spocky/miproja1/assets/37216364/a4a9a059-be2c-4c87-a3ec-6abe6f5f5bfd)
![IMG_20240405_210007758](https://github.com/spocky/miproja1/assets/37216364/8418ea30-e7bd-4073-b550-d07135058db8)
![IMG_20240405_210333782](https://github.com/spocky/miproja1/assets/37216364/2595e60c-be06-4936-ba15-fc2fffc0c0fe)

**Comment by spocky** [comment] 2024-04-05 21:56
Fixed in 4.52, thanks for your feedback !

**Closed by spocky** 2024-04-05 21:56 UTC
