### ISSUE TITLE
How do I buy on a fire stick?

### ISSUE THREAD

**Issue by steve51184** [spocky/miproja1#89] opened 2024-04-07 01:14 UTC
I see the option to buy for Nvidia shield but how can I buy the premium for the apk I sideloaded on my fire stick 4k? Also I don't have to buy it twice do I?

**Comment by spocky** [comment] 2024-04-07 02:18
Duplicate of #5
On Android, your purchase is linked to your Google account. Amazon has decided to go their own way, when Projectivy will be available on Amazon Store, it can't be linked to your Google account, so another purchase will probably be necessary :/

**Closed by spocky** 2024-04-07 02:18 UTC

**Comment by steve51184** [comment] 2024-04-07 02:20
If we submit our email to you it could be linked through right?
