### ISSUE TITLE
BUG: Input options unable to be restored

### ISSUE THREAD

**Issue by kermitstrontium** [spocky/miproja1#100] opened 2024-04-11 13:40 UTC
Input options, once removed this way, cannot be restored without a full reset.

Steps to reproduce:
1. Click Settings (gear in top right)
2. Click Projectivity Launcher settings
3. Click Input settings
4. Click Enable inputs
5. Uncheck any number of inputs
6. Return to Home Screen
7. Observe inputs not visible
8. Return to Input settings
9. Check the previously removed inputs
10. Return to Home Screen
11. Observe inputs still not visible 

Note that hiding and restoring inputs from the left hand menu works as expected.

**Comment by spocky** [comment] 2024-04-11 13:55
Duplicate of #42, fixed in 4.5x+

**Closed by spocky** 2024-04-11 13:55 UTC
