### ISSUE TITLE
Editing settings often loses the background

### ISSUE THREAD

**Issue by kindall** [spocky/miproja1#78] opened 2024-04-04 03:25 UTC
When you edit Projectivy settings and come back to the home screen, it's a crapshoot whether your custom background will still be shown.

The background setting is still correct and the background eventually comes back but it's kinda annoying.

Projectivy 4.5.1, CCwGTV

**Comment by spocky** [comment] 2024-04-04 15:58
Duplicate of #67, fixed in upcoming 4.52

**Closed by spocky** 2024-04-04 15:58 UTC
