### ISSUE TITLE
Disabled input cannot be re-enabled without wiping settings

### ISSUE THREAD

**Issue by martindmtrv** [spocky/miproja1#42] opened 2023-11-28 04:19 UTC
Hey there, I'm running Projectivy launcher premium (4.3.6) on my TCL Android TV

I'm having an issue where if an input is disabled, there is no way to re-enable it without resetting to default settings

From a fresh reset:

1. Open projetivity settings > input > enable inputs
2. Disable an input
3. Return home, input will be hidden now
4. Go back to settings > input > enable inputs 
5. Renable the input
6. Return home, the input is still hidden

If you stay within settings (just back out of the enable input menu and go back) instead of going back home, the toggle flips back to disabled and there's no way to re-enable it

Workaround as mentioned is to reset to default settings in settings > manage settings > reset to default but it is a bit cumbersome to have to reconfigure everything

Probably most do not encounter this but I had HDMI inputs hidden when nothing was plugged into them, I recently added a new input to my TV and when trying to re-enable it found the bug

**Comment by githottub** [comment] 2024-03-06 17:26
I can confirm this bug on a different brand of TV; therefore, it's not just TCL. 

I accidentally unchecked an HDMI input. Upon seeing it missing from the home screen, I returned to the Projectivy settings to re-enable it. Although its checkbox does check when pressing the OK button on it, regardless of whether you back out of the menu or use the Home button, it does not retain the check in the box and therefore the input is never re-enabled. I confirmed this again purposely with another input and confirmed it after a reboot of the TV.

**Comment by martindmtrv** [comment] 2024-03-07 20:49
Here's a video showing it


https://github.com/spocky/miproja1/assets/36076588/6343b699-8a2e-44f8-b674-74506366b093

**Comment by martindmtrv** [comment] 2024-03-07 20:49
Initially it is enabled after disabling it can't get it back unless I restore from exporting settings

**Comment by githottub** [comment] 2024-03-09 17:24
@spocky What's shown in the video is the same thing happening to me. 

@martindmtrv Since it's disabled when you export settings, isn't it still disabled when you restore them? I haven't tried it yet because I figured that's what would happen.

**Comment by martindmtrv** [comment] 2024-03-09 23:24
Yeah I tried out this

1. Start with all inputs enabled
2. Disable one input
3. Try to re-enable it (same behavior as video)
4. Export settings
5. Import settings
6. It's still stuck as disabled (same as video)

The only way to get it back is to restore an exported setting before you disabled the input or to reset settings completely

**Comment by martindmtrv** [comment] 2024-03-09 23:26
I haven't looked at the code or anything yet but possibly disabling it removes an object from a list of objects somewhere and then on re-enabling it tries to set a boolean inside that object but fails because it was removed from the list? 

I don't know how to pull logs here but that's my suspicion of what's happening. Is the exported settings file just plaintext JSON? If so I can move it off my tv to take a look inside

**Comment by githottub** [comment] 2024-03-11 17:58
I copied the exported settings file from the TV to my PC but, infortunately, it's not just plaintext JSON. I had hoped it would be so I could modify it to re-enable the inputs, copy it back to the TV then restore from it. Since I really don't want to completely reset Projectivy and start from scratch, I'm hoping @spocky will be able to fix this bug.

**Comment by spocky** [comment] 2024-03-22 12:07
Should be fixed in 4.50

**Closed by spocky** 2024-03-22 12:07 UTC
