### ISSUE TITLE
Stuck on black screen

### ISSUE THREAD

**Issue by Wielder4201** [spocky/miproja1#86] opened 2024-04-06 18:53 UTC
I just updated to the latest version from github and it got stuck on black screen, TV remote became unresponsive, I had to restart TV. After restarting it was still got stuck on black screen since projectivy was the only launcher I had (disabled android TV Home) and I had a brief window of about 10-15 seconds before the UI and my remote became unresponsive. Tried restarting a few times before I had to remotely install Flauncher from playstore, then set Flauncher as default and switched to it in that brief window, uninstalled latest projectivy, then reinstalled the previous version.

TV details - Hisense Android version 9
Let me know if any more details are needed.
Thanks in advance!

**Comment by spocky** [comment] 2024-04-06 23:37
Duplicate of #84 fixed in 4.53

**Closed by spocky** 2024-04-06 23:37 UTC
