### ISSUE TITLE
Picking folder for ccwgt

### ISSUE THREAD

**Issue by Glx28** [spocky/miproja1#83] opened 2024-04-05 11:02 UTC
I get an error on ccwgtv for 4.5.1 the premium version choosing a folder for wallpapers, when I pick user defined folder I get "you don't have an app that can do this" I am using file manager + but I have tried many different ones. I can pick a local image or video but not a folder.

**Comment by spocky** [comment] 2024-04-05 21:56
Duplicate of #69

**Closed by spocky** 2024-04-05 21:56 UTC
